### ISSUE TITLE
The game cannot be launched without internet connection

### ISSUE THREAD

**Issue by Gbr22** [skmedix/SKlauncher#45]
The launcher can be, but the game cannot be launched without an internet connection.

**Comment by skmedix** [comment]
Should be fixed in next update

**Comment by skmedix** [comment]
Fixed in last stable `3.0.0-f8aacaa`

**Comment by atesin** [comment]
the issue still persist, i was about to create a new issue but found this

i moved to a new house in the country without internet, i am developing a bukkit plugin so i need to launch the game to debug...

it launches, but in about a month later it crashes again and exits immediately, so i have to go to the town to get internet and open the launcher so the game updates and works offline again

**Comment by atesin** [comment]
more info that could be related to this problem...

```
[SKlauncher] Checking connection..
[SKlauncher] Connecting...
[SKlauncher] java.net.UnknownHostException: api.skmedix.pl
	(...)
	at pl.skmedix.bootstrap.BootstrapUtils.checkNetwork(BootstrapUtils.java:109)
	(...)
	
[SKlauncher] Response code: 0 - offline
[SKlauncher] Connecting...
[SKlauncher] java.net.UnknownHostException: bitbucket.org
	(...)
	at pl.skmedix.bootstrap.BootstrapUtils.checkNetwork(BootstrapUtils.java:109)
	(...)
	
[SKlauncher] Response code: 0 - offline
[SKlauncher] Currently we're not able to connect to our server.
[SKlauncher] Server is OFFLINE and you don't have local saved data
[SKlauncher] Cannot read data
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = JavaFX Application Thread
	at com.sun.glass.ui.Application.checkEventThread(Application.java:443)
	(...)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at pl.skmedix.bootstrap.BootstrapFXUtils.lambda$displayWarning$2(BootstrapFXUtils.java:125)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	(...)
```

**Comment by atesin** [comment]
i am not sure this is fixed and the issue is resolved .... 

i discovered everytime the launcher starts, it checks the modification date of "(minecraft-dir)/sklauncher/sklauncher.data" file, and if is older than XX days (30?, or in fixed dates?) the launcher files are deleted and can't launch the game

if you were not careful in backuping the files before, then the only way to restore them and launch the game is to run the launcher again but CONNECTED TO INTERNET

```
...
[SKlauncher] Response code: 0 - offline
[SKlauncher] Currently we're not able to connect to our server.
[SKlauncher] Local saved data is too old, deleting
[SKlauncher] Cannot read data
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = JavaFX Application Thread
...
```
